# configuration file
from src.enums.Enums import Appearance

# API settings
BACKEND_URL         = "http://localhost:8080"
BACKEND_URL_HTTPS   = "https://localhost:8080"
REQUEST_TIMEOUT     = 3  # seconds

# WINDOW settings
WINDOW_TITLE = "CLEANER APP"
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 700
MIN_WIDTH = 800
MIN_HEIGHT = 600

# TOP menu settings
TOP_MENU_HEIGHT = 60
TOP_MENU_CORNER_RADIUS = 0

# button `clean`
TOP_MENU_BUTTON_CLEAN_WIDTH = 120
TOP_MENU_BUTTON_CLEAN_HEIGHT = 50

# button `analyze`
TOP_MENU_BUTTON_ANALYZE_WIDTH = 110
TOP_MENU_BUTTON_ANALYZE_HEIGHT = 50

# button `clear_options`
TOP_MENU_BUTTON_CLEAR_OPTIONS_WIDTH = 120
TOP_MENU_BUTTON_CLEAR_OPTIONS_HEIGHT = 50

# button `settings`
TOP_MENU_BUTTON_SETTINGS_WIDTH = 100
TOP_MENU_BUTTON_SETTINGS_HEIGHT = 50

# LEFT menu settings
LEFT_MENU_WIDTH = 250
LEFT_MENU_CORNER_RADIUS = 0

# MAIN menu settings
MAIN_MENU_CORNER_RADIUS = 0

# SETTINGS window settings
SETTINGS_WINDOW_TITLE = "Settings"
SETTINGS_WINDOW_WIDTH = 800
SETTINGS_WINDOW_HEIGHT = 600
SETTINGS_APPEARANCE_MODE_OPTION_MENU_WIDTH = 140

# THEME settings
THEME_DIRECTORY = "resources/themes"
APPEARANCE_MODE = Appearance.DARK

